// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30Y_asXANqT0fdsl1KErZND5PW53axGc',
    appId: '1:180285242790:web:ba59f3179613c0d961e367',
    messagingSenderId: '180285242790',
    projectId: 'firebase-ipssi',
    authDomain: 'fir-ipssi.firebaseapp.com',
    storageBucket: 'firebase-ipssi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFylTxeEOX93JmQuhIZ8sDU04GLxnqna4',
    appId: '1:180285242790:android:fcbdc56efa3e62e661e367',
    messagingSenderId: '180285242790',
    projectId: 'firebase-ipssi',
    storageBucket: 'firebase-ipssi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuSdAHQMfR2ZiG2HZNl8dl2pzs_vUlvaQ',
    appId: '1:180285242790:ios:2f5f5f27ada6e93761e367',
    messagingSenderId: '180285242790',
    projectId: 'firebase-ipssi',
    storageBucket: 'firebase-ipssi.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuSdAHQMfR2ZiG2HZNl8dl2pzs_vUlvaQ',
    appId: '1:180285242790:ios:2f5f5f27ada6e93761e367',
    messagingSenderId: '180285242790',
    projectId: 'firebase-ipssi',
    storageBucket: 'firebase-ipssi.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB30Y_asXANqT0fdsl1KErZND5PW53axGc',
    appId: '1:180285242790:web:6020dbb7d28d44d761e367',
    messagingSenderId: '180285242790',
    projectId: 'firebase-ipssi',
    authDomain: 'fir-ipssi.firebaseapp.com',
    storageBucket: 'firebase-ipssi.appspot.com',
  );

}